### PR TITLE
refactor: macos fixes

### LINKED ISSUE #55: v1 finalization
## TODO
- [x] Update README + write unit test to verify it works as expected
- [x] Test MacOS + Linux
- [x] Set working dir flag (verify exists first)

### PR DESCRIPTION
**Pull request by reecepbcups**
closes https://github.com/Reecepbcups/docci/issues/55

### CODE REVIEW

File: parser/script_templates.go [hunk 1]
```diff
@@ -27,8 +27,8 @@ fi
 
 	// Background block template
 	backgroundBlockTemplate = `# Background block {{INDEX}}{{FILE_INFO}}
-setsid bash -c '{
```
Comment (reecepbcups) [inline parser/script_templates.go:30]: this did not work on macos
